exec-once=~/.config/mango/monitors.sh
exec=bash ~/.config/mango/autostart.sh

# Appearance
gappih=3
gappiv=3
gappoh=3
gappov=3
borderpx=5
border_radius=0
no_border_when_single=1

# Window effect
blur=10

# Animations
animation_duration_move=200
animation_duration_open=200
animation_duration_tag=350
animation_duration_close=200
animation_duration_focus=0

# Colors
source=~/.cache/wal/colors-mango.conf

# Master-Stack Layout Setting
new_is_master=0
default_mfact=0.50

# Keyboard
repeat_rate=50
repeat_delay=400

# Keybinds
source=~/.config/mango/keybinds.conf

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

