"$schema" = 'https://starship.rs/config-schema.json'

format = """\
$username\
$hostname\
$directory\
$character"""

[username]
show_always = false
style_root = "white"
format = '[ $user](1)'

[hostname]
ssh_only = true
format = "[@$hostname](4)"

[directory]
style = "white"
format = "[ $path ](1)"
truncation_length = 5
truncation_symbol = "…/"
